import type { Metadata } from 'next';
import './globals.css';
import AppBar from '@/components/AppBar';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-gray-900 min-h-screen">
        <AppBar />
        <div className="w-full h-screen pt-30 p-4 lg:px-10  bg-gray-900">{children}</div>
      </body>
    </html>
  );
}
